// Copyright 2013 Michel Kraemer
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package de.undercouch.citeproc.mendeley;

import java.io.IOException;
import java.util.List;

/**
 * Reads documents from the Mendeley REST services. Needs an OAuth API key and
 * secret in order to authenticate. Users of this class should
 * <a href="http://dev.mendeley.com/">register their app</a> to receive such a
 * key and secret.
 * @author Michel Kraemer
 */
public interface MendeleyConnector {
	/**
	 * Gets a new authorization URL from the Mendeley server. This is the
	 * first step in the OAuth authorization process. The user has to
	 * visit the authorization URL and grant access to this app. Then they
	 * will get an verification code which has to be passed to {@link #authorize(String)}
	 * @return the URL the authorization URL
	 */
	String getAuthorizationURL();

	/**
	 * Authorizes the app. This is the third step in the OAuth authorization
	 * process. After the user has visited the authorization URL that was
	 * generated by {@link #getAuthorizationURL()}, this method has to be
	 * called to finish authorization
	 * @param verificationCode the verification code the user received from
	 * the authorization URL
	 */
	void authorize(String verificationCode);

	/**
	 * <p>Authorizes the app. If you already know a valid OAuth access token
	 * (for example if you cached it from previous sessions) you may call
	 * this method instead of {@link #getAuthorizationURL()} and
	 * {@link #authorize(String)}.</p>
	 * <p>This method just saves the provided access token. It does not
	 * act with the Mendeley REST services in any way.</p>
	 * @see #getAccessTokenValue()
	 * @see #getAccessTokenSecret()
	 * @param token the access token value
	 * @param secret the access token's secret
	 */
	void setAccessToken(String token, String secret);
	
	/**
	 * @return the access token's value used for authentication or null if
	 * the app is not yet authenticated
	 * @see #setAccessToken(String, String)
	 */
	String getAccessTokenValue();
	
	/**
	 * @return the access token's secret used for authentication or null if
	 * the app is not yet authenticated
	 * @see #setAccessToken(String, String)
	 */
	String getAccessTokenSecret();

	/**
	 * Requests a list of document IDs from the server. The user has to be
	 * authenticated before this method can be called.
	 * @return the document IDs
	 * @throws UnauthorizedException if the user is not authenticated
	 * @throws MendeleyRequestException if the server returns an error code
	 * @throws IOException if the documents could not be read from the server
	 */
	List<String> getDocuments() throws MendeleyRequestException, IOException;
}
